### ISSUE TITLE
9.6.1 breaks tests with ngrx

### ISSUE THREAD

**Issue by vokeit-gschuster** [ike18t/ng-mocks#142] opened 2020-06-18 13:43 UTC
We upgraded ng-mocks to 9.6.1 today and several (about 10 of ~700) tests break because of ngrx missing injection tokens:
```
NullInjectorError: R3InjectorError(DynamicTestModule)[StoreFeatureModule -> InjectionToken @ngrx/store Internal Store Features -> InjectionToken @ngrx/store Internal Store Features]:
          NullInjectorError: No provider for InjectionToken @ngrx/store Internal Store Features!
        error properties: Object({ originalStack: 'Error: NullInjectorError: No provider for InjectionToken @ngrx/store Internal Store Features!
```
These now failing tests work absolutely fine with 9.5.0, @ngrx/effects 9.2.0 and @ngrx/store 9.2.0.
I see that the Module mock has been totally refactored and as far as I can tell it now seems to sometimes miss the given imports of StoreModule.forRoot(), StoreModule.forFeature(), EffectsModule.forRoot() and EffectsModule.forFeature().

**Comment by satanTime** [comment] 2020-06-18 13:50
Hi,

thank you for the report.
might you provide an example of a failing test and how ng-mocks is used there?

I have tests with `StoreModule.forRoot()`, `StoreModule.forFeature()`, `EffectsModule.forRoot()` and `EffectsModule.forFeature()` and, unfortunately, they don't show the issue.

**Comment by vokeit-gschuster** [comment] 2020-06-18 14:06
I'll see if I can extract such a test.

**Comment by satanTime** [comment] 2020-06-18 14:08
Thanks, I think if you should how TestBed is setup and how module imports / declarations looks like it should be enough. Perhaps I'm missing something in my setup.

**Comment by vokeit-gschuster** [comment] 2020-06-18 14:17
Test for MyComponent (in MyModule) fails with mocked "MyOtherModule" that has ngrx integrated.

```
describe('MyComponent', () => {
  TestBed.configureTestingModule({
    imports: [
      MockModule(MyOtherModule),
      HttpClientTestingModule
    ],
    declarations: [
      MyComponent,
      MyOtherComponent
    ],
    providers: [
      provideMockStore<AppState>(getMockState())
    ]
  })
  .compileComponents();

  //...
});

@NgModule({
  imports: [
    CommonModule,
    StoreModule.forFeature('xyz', xyzReducer),
    EffectsModule.forFeature([XyzEffects])
  ],
  providers: [
    XyzService
  ],
  declarations: [
    XyzComponent
  ],
  exports: [
    XyzComponent
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class MyOtherModule { }
```

**Comment by satanTime** [comment] 2020-06-18 19:56
Thanks, I was able to reproduce the issue, working on the fix.

**Comment by satanTime** [comment] 2020-06-18 21:26
Hi, again, might you verify the fix? Simply unpack it and put under `node_modules`.
[ng-mocks.zip](https://github.com/ike18t/ng-mocks/files/4801265/ng-mocks.zip)

**Comment by vokeit-gschuster** [comment] 2020-06-19 08:04
Yes, fixed these problems.
I only have one test left that doesn't work because a form click on a radio box is not registered, don't know if that has something to do with ng-mocks.
If I find that it is caused by ng-mocks I'll open a new ticket.

Thanks for your quick fix!

**Comment by satanTime** [comment] 2020-06-19 08:30
Cool, the fix will be released on Sunday. About the form - might you share the test and the template of its component?

**Closed** 2020-06-20 08:45 UTC
Labels: bug

**Comment by satanTime** [comment] 2020-06-21 17:27
Hi there, 9.6.2 has been released. Please let me know how it works for you.
