### ISSUE TITLE
Mock fails

### ISSUE THREAD

**Issue by syrok0010** [ike18t/ng-mocks#1711] opened 2022-01-27 20:52 UTC
The mock doesn't work with the following configuration
```
beforeEach(async () => {
    await TestBed.configureTestingModule({
      declarations: [
        CreateBusComponent,
        MockComponent(BusSchemaComponent),
        MockComponent(BusFormCoreComponent),
        MockDirective(TuiButtonComponent),
      ],
      imports: [
        MockModule(TuiNotificationsModule),
      ],
      providers: [
        MockProvider(SnackbarService, { })
      ]
    }).compileComponents();
  });
```

and the following

```
beforeEach(() =>
    MockBuilder(CreateBusComponent, [
      BusModule,
      AdminPanelModule,
      AppModule,
    ]).provide({ provide: SnackbarService, useValue: {} })
  );
```

with the same error

```
TypeError: Cannot set property ɵprov of function AbstractTuiDialogService(idService) {
                var _this = _super.call(this, function (observer) { ...<omitted>... } which has only a getter

      1 | import { Injectable } from "@angular/core";
    > 2 | import { TuiNotification, TuiNotificationsService } from "@taiga-ui/core";
        | ^
      3 |
      4 | @Injectable({
      5 |   providedIn: "root",

      at node_modules/@taiga-ui/core/bundles/taiga-ui-core-components-dialog.umd.js:402:32
      at node_modules/@taiga-ui/core/bundles/ng:/@taiga-ui/core/components/dialog/dialog.service.ts:24:2
      at node_modules/@taiga-ui/core/bundles/taiga-ui-core-components-dialog.umd.js:2:68
      at Object.<anonymous> (node_modules/@taiga-ui/core/bundles/taiga-ui-core-components-dialog.umd.js:5:2)
      at node_modules/@taiga-ui/core/bundles/taiga-ui-core-components.umd.js:2:222
      at Object.<anonymous> (node_modules/@taiga-ui/core/bundles/taiga-ui-core-components.umd.js:5:2)
      at node_modules/@taiga-ui/core/bundles/taiga-ui-core.umd.js:2:156
      at Object.<anonymous> (node_modules/@taiga-ui/core/bundles/taiga-ui-core.umd.js:5:2)
      at Object.<anonymous> (src/app/common/snackbar.service.ts:2:1)
      at Object.<anonymous> (src/app/admin-panel/bus/create-bus/create-bus.component.ts:3:1)
      at Object.<anonymous> (src/app/admin-panel/bus/create-bus/create-bus.component.spec.ts:9:1)
```

**Comment by satanTime** [comment] 2022-01-27 21:30
Hi @syrok0010,

Thanks for the report. Might you provide a repo / stackblitz with a min example?

**Comment by syrok0010** [comment] 2022-01-28 13:00
@satanTime, https://github.com/syrok0010/ng-mocks-sample

**Comment by satanTime** [comment] 2022-01-28 13:03
Great thanks!!!

**Comment by satanTime** [comment] 2022-01-29 16:56
Hi @syrok0010,

for me it fails a bit differently: 

```
 FAIL  src/app/app.component.spec.ts
  ● Test suite failed to run

    Cannot set base providers because it has already been called

    > 1 | import "jest-preset-angular/setup-jest";
        | ^
      2 | import { ngMocks } from "ng-mocks";
      3 |
      4 | ngMocks.autoSpy("jest");

      at TestBedRender3.initTestEnvironment (node_modules/@angular/core/fesm2015/testing.mjs:1643:19)
      at Object.<anonymous> (node_modules/jest-preset-angular/setup-jest.js:1:100)
      at Object.<anonymous> (setup-jest.ts:1:1)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:320:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:173:3)
```

might you fix this part? I'll be working on that too.

**Comment by satanTime** [comment] 2022-01-29 17:08
yep - got the error

```
 FAIL  src/app/app.component.spec.ts
  ● Test suite failed to run

    TypeError: Cannot set property ɵprov of function AbstractTuiDialogService(idService) {
                var _this = _super.call(this, function (observer) { ...<omitted>... } which has only a getter

      1 | import { NgDompurifySanitizer } from "@tinkoff/ng-dompurify";
      2 | import { BrowserAnimationsModule } from "@angular/platform-browser/animations";
    > 3 | import { TuiRootModule, TuiDialogModule, TuiNotificationsModule, TUI_SANITIZER } from "@taiga-ui/core";
        | ^
      4 | import { NgModule } from '@angular/core';
      5 | import { BrowserModule } from '@angular/platform-browser';
      6 |

      at node_modules/@taiga-ui/core/bundles/taiga-ui-core-components-dialog.umd.js:402:32
      at node_modules/@taiga-ui/core/bundles/ng:/@taiga-ui/core/components/dialog/dialog.service.ts:24:2
      at node_modules/@taiga-ui/core/bundles/taiga-ui-core-components-dialog.umd.js:2:68
      at Object.<anonymous> (node_modules/@taiga-ui/core/bundles/taiga-ui-core-components-dialog.umd.js:5:2)
      at node_modules/@taiga-ui/core/bundles/taiga-ui-core-components.umd.js:2:222
      at Object.<anonymous> (node_modules/@taiga-ui/core/bundles/taiga-ui-core-components.umd.js:5:2)
      at node_modules/@taiga-ui/core/bundles/taiga-ui-core.umd.js:2:156
      at Object.<anonymous> (node_modules/@taiga-ui/core/bundles/taiga-ui-core.umd.js:5:2)
      at Object.<anonymous> (src/app/app.module.ts:3:1)
      at Object.<anonymous> (src/app/app.component.spec.ts:3:1)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:320:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:173:3)
```

working on the fix.

**Comment by satanTime** [comment] 2022-01-29 17:14
So, unfortunately nothing can be done on `ng-mocks` side.

Because the issue is in declarations of the service, and they are loaded on the import of `app.component.ts`.

A test without `ng-mocks`.

```
import {AppComponent} from './app.component';
import {AppModule} from "./app.module";
import {TestBed} from "@angular/core/testing";

describe('AppComponent', () => {
  beforeEach(() => TestBed.configureTestingModule({
    imports: [AppModule],
    declarations: [AppComponent],
  }));

  it('should create the app', () => {
    const fixture = TestBed.createComponent(AppComponent);
    fixture.detectChanges();
    const app = fixture.componentInstance;
    expect(app).toBeTruthy();
  });
});
```

I'll close this issue for now. Feel free to reopen it if nothing has been discovered in https://github.com/Tinkoff/taiga-ui/issues/1257.

**Closed by satanTime** 2022-01-29 17:14 UTC
