### ISSUE TITLE
Mocking modules with entry components

### ISSUE THREAD

**Issue by IlCallo** [ike18t/ng-mocks#51] opened 2019-05-13 11:11 UTC
I'm trying to mock a Module which contains an entry component (used for a `MatDialog`), but `MockModule` seems to erase in some way the original `entryComponents` definition.
Is it intended behaviour?

```ts
@NgModule({
  declarations: [MyComponent],
  entryComponents: [MyComponent]
})
class TestModule {}

// From https://github.com/NetanelBasal/spectator
const spectator = createService({
    service: MyService,
    imports: [NoopAnimationsModule, MatDialogModule, MockModule(TestModule)]
  });
```

I get `No component factory found for MyComponent. Did you add it to @NgModule.entryComponents?`

**Comment by NetanelBasal** [comment] 2019-05-13 12:51
@IlCallo Angular doesn't support `entryComponents` out of the box. In Spectator, we do the job for you.

**Comment by IlCallo** [comment] 2019-05-13 13:21
I see... From https://stackoverflow.com/questions/41483841/providing-entrycomponents-for-a-testbed there seems to be some kind of workaround.

Still, if it's technically feasible in some way (and I don't know if it is), shouldn't entry components mocking be in the scope of this package?

**Comment by ike18t** [comment] 2019-05-14 11:15
Hey @IlCallo ,

I added entryComponents to mocked modules and it was released in https://github.com/ike18t/ng-mocks/releases/tag/v7.8.0

**Comment by IlCallo** [comment] 2019-06-10 16:38
Hey @ike18t, we are having some troubles when testing `MatDialog` and mocking the component, possibly related to how you provide the mocked component.
Could you jump in into https://github.com/NetanelBasal/spectator/issues/106 and help us when you have time?

**Comment by ike18t** [comment] 2019-06-10 19:42
@IlCallo Not sure if you saw my response in that issue (which is now closed):

I don't have any experience using Angular Material but I do see that I can get the component's providers via the MockDirectiveResolver...that may be a slippery slope of needing to know what providers to mock vs what not to mock though.

**Comment by IlCallo** [comment] 2019-06-11 09:42
Many "popup" stuff in Angular Material is created using portals, which are some kind of slots where you can render dynamic content, obtained via Dependency Injection.

If those components aren't used anywhere else in a static way, Angular static compiler won't create a the required component factory function (which contains the metadata telling Angular how to render a component, which will probably be removed when Ivy compiler becomes the default) and you are supposed to explicitly tell the system to create them using `entryComponents` option.

That's a brief explanation to give you context about the use case.

Can you better explain the "slippery slope" part and how does `MockDirectiveResolver` relates to Angular Injection System?
Sorry for delayed answers, but we have 6h timezone difference between us :)

**Comment by scote** [comment] 2020-01-09 17:21
I am facing the same issue. Is there any update on that?

**Comment by satanTime** [comment] 2020-02-20 19:48
At leat for Angular 9 there's no issue anymore: they say `entryComponents` `* @deprecated Since 9.0.0. With Ivy, this property is no longer necessary.` but it requires this PR https://github.com/ike18t/ng-mocks/pull/80.
With Angular 8 I was able to reproduce `Failed: Cannot read property 'indexOf' of undefined`. Working on fix.

**Comment by satanTime** [comment] 2020-02-20 19:59
Added fix to the same PR, it requires to avoid mock of the 'InjectionToken HammerGestureConfig' provider.

**Closed** 2020-03-21 08:49 UTC
