### ISSUE TITLE
MockProvider does not reset the token value of MockInstance

### ISSUE THREAD

**Issue by AE1NS** [ike18t/ng-mocks#1256] opened 2021-10-19 08:35 UTC
First of all, thank you for this awesome plugin. We integrated it in our solutions and its working really great! Unfortunately one thing is not working as I expect it, but maybe its not a bug, but i missunderstood it.

I created an angular injection token and mock it with MockProvider, i.e.
```
beforeEach(() => {
    TestBed.configureTestingModule({
        providers: [
            MockProvider(myToken, { test: 1 })
        ],
    });
});
```
Inside an 'it' I override it with another value:
`MockInstance(myToken, () => ({ test: 2 }));`

When the next 'it' runs, I expect the value to be resettet to '{ test: 1 }' again by the MockProvider call in beforeEach, but I still get the value '{ test: 2 }' here.

Am I using this the wrong way or is this a bug of the framework?

**Comment by satanTime** [comment] 2021-10-20 19:09
Hi @AE1NS,

if you don't install scopes for `MockInstance`, then this is the cause of the issue.

If you use jasmine, then everything is every easy, you need to add a global reportor: https://ng-mocks.sudo.eu/extra/install#default-customizations

```ts
// auto restore for jasmine and jest <27
// declare const jasmine: any;
jasmine.getEnv().addReporter({
  specDone: MockInstance.restore,
  specStarted: MockInstance.remember,
  suiteDone: MockInstance.restore,
  suiteStarted: MockInstance.remember,
});
```

The same solution works for jest < 27, if you are using jest 27+, then please support this issue: https://github.com/facebook/jest/issues/11483.
Until the issue has been merged and released, you could use scopes: https://ng-mocks.sudo.eu/api/MockInstance#customization-scopes

```ts
describe('suite', () => {
  beforeAll(MockInstance.remember);
  afterAll(MockInstance.restore);
  // ...
});
```

Please let me know if it helps, or you need further assistance.

**Comment by AE1NS** [comment] 2021-10-21 04:50
Thank you for your response.
We are using jasmine and I forgot to mention that we are using version 12.3.1 right now, because there seems to be some work to update to 12.4+.
I will try to update to the new version and use the scopes.

**Comment by satanTime** [comment] 2021-10-21 06:26
Hi @AE1NS,

I see, might you provide a test with the issue?

Also, could you try to use `MockReset` in `afterEach`? It should remove any customizations registered via `MockInstance`.

**Comment by satanTime** [comment] 2021-10-21 07:51
Ah sorry. My mistake. It should be

afterEach(MockReset);

**Comment by satanTime** [comment] 2022-02-01 20:47
Hi there, a happy new year! :) 

I'm back to business and was able to reproduce your issue. It should be fixed soon.

**Comment by satanTime** [comment] 2022-02-02 06:33
the issue here is that `MockInstance` with callbacks doesn't follow scopes, it will be fixed.

for now, you could use `MockInstance(MyToken, 'test', 2);`, it works with classes, but not sure yet about tokens :)

**Closed** 2022-03-06 19:18 UTC

**Comment by satanTime** [comment] 2022-03-06 19:30
[v13.1.0](https://github.com/ike18t/ng-mocks/releases/tag/v13.1.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
