### ISSUE TITLE
Testcases are failing after upgrading to 11.1+

### ISSUE THREAD

**Issue by vinayk406** [ike18t/ng-mocks#567] opened 2021-05-18 07:04 UTC
Testcases are failing with below exception after upgrading to 11.1+ version. 

```error
@Component: ___Component
✗ ngOnInit (82ms)
SyntaxError: Unexpected identifier
    at <Jasmine>
    at JitEvaluator.evaluateCode (http://localhost:9876/_karma_webpack_/vendor.js:10798:20)
    at JitEvaluator.evaluateStatements (http://localhost:9876/_karma_webpack_/vendor.js:10768:21)
    at CompilerFacadeImpl.jitExpression (http://localhost:9876/_karma_webpack_/vendor.js:23362:39)

Error: <spyOn> : could not find an object to spy upon for dispatch()
Usage: spyOn(<object>, <methodName>)
Error: <spyOn> : could not find an object to spy upon for dispatch()
Usage: spyOn(<object>, <methodName>)
    at <Jasmine>
```

Testcases are working as expected with version `11.10.0`

**Comment by satanTime** [comment] 2021-05-18 07:15
Hi @vinayk406,

thanks for the report. Might you provide more info about the test? 
`ng-mocks` doesn't use `spyOn`, so I think, the issue is related to some particular setup.

**Comment by satanTime** [comment] 2021-05-18 09:26
this is the problem `'seriesTooltipTemplate'.replace(new RegExp('[^a-z0-9-_]+', 'mg'), ' ').trim().replace(' ', '_')` which should be fixed properly.

**Comment by satanTime** [comment] 2021-05-18 17:50
Hi @vinayk406,

could you verify that the fix works correctly on your project? 
[ng-mocks.zip](https://github.com/ike18t/ng-mocks/files/6503289/ng-mocks.zip)

Thanks in advance!

**Closed** 2021-05-19 15:15 UTC

**Comment by satanTime** [comment] 2021-05-21 07:26
[v12.0.1](https://github.com/ike18t/ng-mocks/releases/tag/v12.0.1) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
