### ISSUE TITLE
Typed access for auto-spied services

### ISSUE THREAD

**Issue by urbspower** [ike18t/ng-mocks#1836] opened 2022-02-11 16:42 UTC
Hi!

I am aware that mocked services can be auto-spied like https://ng-mocks.sudo.eu/extra/auto-spy. I am wondering though how to retrieve the mocked service correctly typed. Is this possible? Or is the following code snippet the suggested approach?

```
const fixture = MockRender(MyComponent);
const myService = fixture.point.injector.get(MyService);
(myService as jasmine.Spy).and.returnValue(...);
```

Thanks. Greets Lukas

**Comment by satanTime** [comment] 2022-02-13 11:22
Hi @urbspower,

this is a common problem and the issue is that you use jasmine, someone uses jest, others use sinon, etc.

Therefore, everyone decides the best way to cast types.

For example, you could consider [`ngMocks.stubMember`](https://ng-mocks.sudo.eu/api/ngMocks/stubMember) or (`MockInstance`)[https://ng-mocks.sudo.eu/api/MockInstance#set-desired-values], they allow to follow types of spies.

**Comment by satanTime** [comment] 2022-02-20 15:43
Hi @urbspower,

I'm going to close the issue. Feel free to write comments if anything should be clarified / discussed.

**Closed by satanTime** 2022-02-20 15:43 UTC
