### ISSUE TITLE
stackblitz live example link broken

### ISSUE THREAD

**Issue by sapatgit** [ike18t/ng-mocks#868] opened 2021-07-26 07:37 UTC
## Tested in:

1. Chrome v92.0.4515.107
2. Firefox v90.0.2

### Screenshot:
![Screenshot](https://user-images.githubusercontent.com/21025626/126950425-54277100-4ba4-45ae-9030-dc412048fa8b.png)

**Comment by satanTime** [comment] 2021-07-26 07:47
Hi, thanks for the report.

I've opened a ticket in their repo: https://github.com/stackblitz/core/issues/1561

For now you could use code sandbox link.

**Comment by satanTime** [comment] 2021-07-30 17:29
Glad to announce that they've fixed the issue.

**Comment by clabough** [comment] 2021-12-15 06:15
This is broken again.

**Comment by satanTime** [comment] 2021-12-15 07:47
Hi @clabough, thanks for noticing it!

**Comment by patelvimal** [comment] 2021-12-27 15:08
@satanTime  May I know what exactly needs to be fixed in this, is the issue with stackblitz?. I would be happy to raise the PR.

**Comment by satanTime** [comment] 2021-12-27 19:49
Hi @patelvimal,

thanks for asking. The example repo is here: https://github.com/ng-mocks/examples

In order to fix the issue:
- you need to investigate how stackblitz imports projects from github
- configure your work with stackblitz
- find in history of commits a working commit with stackblitz
- update dependencies one by one to find the dependency which causes the failure
- create a PR
- profit

I faced a similar issue in the past. Not sure what was the issue exactly, but my assumption was a broken internal npm repo on their side
Here you can find more info: 
- https://github.com/stackblitz/core/issues/1561
- https://github.com/stackblitz/core/issues/1562

**Comment by patelvimal** [comment] 2021-12-28 14:15
@satanTime  thanks for the all the information. This is really helpful. Let me dig into it and if I able to fix it will raise the PR.

**Comment by satanTime** [comment] 2022-01-16 16:39
should work well now

**Closed by satanTime** 2022-01-16 16:39 UTC
Labels: good first issue

**Comment by patelvimal** [comment] 2022-01-16 17:21
May I know what changes you have made to make it work? Stackblitz webcontainer just does not work for me at all.

**Comment by satanTime** [comment] 2022-01-16 17:24
I updated `ng-mocks` and `core-js` to the latest versions. I think the error was caused by older `core-js` version.

**Comment by patelvimal** [comment] 2022-01-17 05:34
> I updated `ng-mocks` and `core-js` to the latest versions. I think the error was caused by older `core-js` version.

Question:- There is no new commit made in master branch, so where does this package version changes were made?

**Comment by satanTime** [comment] 2022-01-17 06:35
It's another repo: https://github.com/ike18t/ng-mocks/issues/868#issuecomment-1001718070
