### ISSUE TITLE
Bug: MockInstance omits type check when returning desired shape

### ISSUE THREAD

**Issue by cyberbiont** [ike18t/ng-mocks#2275] opened 2022-04-18 11:48 UTC
### Description of the bug

maybe I'm missing something, but in case if I need to mock some class instance,
I would expect MockInstance to give me an error if in desired shape I specify the property that doesn't exist

```ts
class Project {
  name = 'Project name'
}

MockInstance(Project, () => ({
  names: 'this property does not exist'
}))
```
It works with single value, though
```ts
MockInstance(Project, 'names', 'this property does not exist') // error ;
```

**Comment by satanTime** [comment] 2022-04-18 13:14
Hi there,

actually it should. Could you try your code on stackblitz or codesandbox playgrounds?

I'll check later on today. Greetings from the Alps.

**Comment by satanTime** [comment] 2022-04-18 13:29
There is our coverage https://github.com/ike18t/ng-mocks/blob/master/tests-failures/mock-instance-service.ts

**Comment by satanTime** [comment] 2022-04-18 18:16
Looks like something is wrong in your project, errors are displayed correctly: https://codesandbox.io/s/infallible-hertz-o6nnm7?file=/src/test.spec.ts

I'm going to close the issue, feel free to reopen with steps how to reproduce it, or a min repo which demonstrates the issue.

**Comment by cyberbiont** [comment] 2022-04-18 20:43
Sorry, bad example from my side. The real issue seems to be more strange.
Errors are not thrown if the mock has at least one correct property specified. Then any extra properties are allowed
If no prop is specified correctly, invalid properties trigger error.
 
```ts
class Project {
	name = 'Project name';
}
MockInstance(Project, () => ({
	name: 'this property does exist', // works
	names: 'this property does not exist', // should throw the error, but doesn't
}));
```

Here's a sandbox that demonstrates this
https://codesandbox.io/s/nice-frog-tri7p5?file=/src/test.spec.ts

**Comment by satanTime** [comment] 2022-04-19 18:56
Ah, I see.

I think, what you are requesting is a typescript feature, and should be changed there:

https://www.typescriptlang.org/play?strict=false&noImplicitAny=false&strictNullChecks=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false&esModuleInterop=false&declaration=false&experimentalDecorators=false&emitDecoratorMetadata=false#code/JYOwLgpgTgZghgYwgAgApQPYCsILMgbwChlTkQ4BbCALmQGcwpQBzAbiIF8iiEMRGyMAAY6ACgCUyALwA+NHChhgcADYAedNlxh505JJnyxxMuSq1kAIkiMrXCR179BYAIzipchUpUatOHh6Bl7GpmQU1HQ2EHYANCQRFvTRtmD0Vgmcjjx8AvhgAEyeRj7KapqYgboyIaUmiaSRsamx6ZkOTnmuAMwl3qiK5f5VOsGG3g3ZbEA

**Comment by cyberbiont** [comment] 2022-04-19 20:02
It works if you specify the return type on the function itself like this
`
const t4 = (): Partial<Project> => ({
    name: "test",
    names: "tests",
});
`
I updated your example

**Comment by satanTime** [comment] 2022-04-19 20:54
Sorry. I didn't get your point. Could you share playground?

**Comment by cyberbiont** [comment] 2022-04-20 16:02
I mean that it is possible to check the return value of the function in the way that we want by specifying the return type on the function declaration rather then on variable like you did in your example (strange that is doesn't work, though).

[playground](https://www.typescriptlang.org/play?strict=false&noImplicitAny=false&strictNullChecks=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false&esModuleInterop=false&declaration=false&experimentalDecorators=false&emitDecoratorMetadata=false#code/JYOwLgpgTgZghgYwgAgApQPYCsILMgbwChlTkQ4BbCALmQGcwpQBzAbiIF8iiEMRGyMAAY6ACgCUyALwA+NHChhgcADYAedNlxh505JJnyxxMuSq1kAIkiMrXCR179BYAIzipchUpUatOHh6Bl7GpmQU1HQ2EHYANCQRFvTRtmD0Vgmcjjx8AvhgAEyeRj7KapqYgboyIaUmiaSRsamx6ZkOTnmuAMwl3qiK5f5VOsGG3g3ZTs75QgAs-fKDvhUBY7WSdCvDldpB9eFNFq3xjebUKdZpGVmOQA)

Also, there's a similar package (not so full-featured as yours) called omnimock, that also allows to automatically get the mock by providing the class to mockInstance() function, and type-checking works correctly there. So I think it's possible to implememnt

**Comment by satanTime** [comment] 2022-04-20 19:45
Looks like we talk about different things. If you check `mockInstance` from `omnimock` it has a different signature: https://github.com/hmil/omnimock/blob/master/src/static-api.ts#L96-L100

it's static, and doesn't allow you to utilize injector when a complex mock needed.

I understand your what you want to have, but doesn't looks like it works in typescript without specifying types.

Your playground, doesn't solve the issue, it is the same as:

```ts
MockInstance(Project, (): Partial<Project> => ({
  name: 'this property does not exist',
  names: 'this property does not exist',
}));
```

**Comment by satanTime** [comment] 2022-04-20 20:14
As an option you can rely on the passed `instance`:

```ts
    MockInstance(Project, (instance) => {
      ngMocks.stub(instance, {
        name: 'this property does not exist',
        names: 'this property does not exist',
      });
    });
```

then it fails.

**Comment by cyberbiont** [comment] 2022-04-26 00:32
OK, I think using `MockInstance(Project, (): Partial<Project> => ({ ... })` is an acceptable workaround, though specifying Partial<> return type seems not very DRY. 
Thanks for the help.

It seems that MockInstance serves the different purpose, but what would then be the closest ng-mock analog to omnimock's 'mockInstance' for mocking the data types like Project?

**Comment by cyberbiont** [comment] 2022-04-29 10:29
OK, answering my own question after digging some more, I think it would be MockService, despite he name. Though it doesn't report 'un-backed' properties access (just returning undefined), I think it has the same purpose
Probably we can close this)

**Comment by satanTime** [comment] 2022-05-01 06:33
Ah, indeed, I forgot about `MockServer`, right, it might be a solution, props are undefined, because they are mock.

However, I would still suggest to use `MockInstance(Class, 'method', 'implementation');`, and in case of removed / renamed members, it will fail as expected.

Thank you for the investigation, closing it.

**Closed by satanTime** 2022-05-01 06:33 UTC
Labels: bug
