### ISSUE TITLE
MockModule creates mocks for imported modules which then creates conflicts

### ISSUE THREAD

**Issue by DaSchTour** [ike18t/ng-mocks#70] opened 2020-01-10 11:29 UTC
If you have a test for Component A which imports a module B as a mock an module C as a non mock module C is not allowed to be part of module B because then a mock for module C is generated which then creates conflicting components.

**Comment by satanTime** [comment] 2020-02-20 22:55
Hi @DaSchTour, you are right, unfortunately, that's a current limitation. Also for the proper correct testing whole environment should be mocked, except testing component.

If you need to avoid a dependency from mocking, I would suggest - declare it right in the `declarations` beside testing component.

Your issue can be closed as a duplicate of https://github.com/ike18t/ng-mocks/issues/44. Once it's implemented you can specify what to mock and what to don't mock without an issue.

**Comment by satanTime** [comment] 2020-03-28 14:47
Hi @DaSchTour,

might you test the issue on 10.0.0-alpha.0 with the MockBuilder https://www.npmjs.com/package/ng-mocks/v/10.0.0-alpha.0#mockbuilder ?

**Comment by satanTime** [comment] 2020-05-09 18:56
Hi @DaSchTour, any update? You can try improved 10.0.0-alpha.3

**Comment by DaSchTour** [comment] 2020-05-11 06:51
Hey, I'll have to check and find my example. Lot of work and lot of refactoring later I can't currently find it. Will need to rebuild it probably. Sorry. Hope I'll find some time for that soon.

**Comment by satanTime** [comment] 2020-05-11 06:54
Totally agree, if you don't mind I would suggest to close the issue and feel free to reopen it or to submit a new one. Quite sure the issue has been fixed, because I met the same problem before.

**Closed** 2020-05-12 14:56 UTC
Labels: bug
