### ISSUE TITLE
False positive ng-mocks not in JIT.

### ISSUE THREAD

**Issue by icorne** [ike18t/ng-mocks#1433] opened 2021-12-02 13:56 UTC
Hello,

After upgrading to the latest release of angular (13.0.2 to 13.0.3) a lot of our tests started failing with:

Error: NavigationComponent declaration has been passed into ng-mocks without Angular decorators. Therefore, it cannot be properly handled. Highly likely, jest.mock() has been used on its file, or ng-mocks is not in JIT mode.

It seems these are false positives, but I don't know why. We're on the last version of jest, jest preset angular and ng-mocks.

**Comment by satanTime** [comment] 2021-12-02 14:59
Hi @icorne 

Thanks for the info. The next week I'm back from vacation and take a look at the issue.

**Comment by stefan-niedermann** [comment] 2021-12-03 07:22
This is a duplicate of #1427.

**Closed** 2021-12-03 07:48 UTC

**Comment by satanTime** [comment] 2022-01-23 16:03
[v13.0.0](https://github.com/ike18t/ng-mocks/releases/tag/v13.0.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
